title: Getting started with python
description: Getting started with python
theme: just-the-docs

url: 

aux_links:
  Template Repository: 

# Color scheme supports "light" (default) and "dark"
# color_scheme: dark
